<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8341f6da-ac82-43c7-953a-8ecf93a20cd3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="Google.Protobuf" Version="3.36.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
    <PackageReference Include="Grpc.Tools" Version="2.84.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
  </ItemGroup>

	<ItemGroup>
		<Protobuf Include="..\Track.proto" GrpcServices="Server" />
		<Protobuf Include="..\Register.proto" GrpcServices="Server" />
		<Protobuf Include="..\RefreshToken.proto" GrpcServices="Server" />
		<Protobuf Include="..\Authentication.proto" GrpcServices="Server" />
		<Protobuf Include="..\logout.proto" GrpcServices="Server" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Services\" />
	</ItemGroup>
	
</Project>
